# Generated by Django 4.0.4 on 2022-10-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name_plural': 'activity types'},
        ),
    ]
