# Generated by Django 4.0.4 on 2022-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possiblereservation',
            name='another_reservation_options',
            field=models.ManyToManyField(blank=True, to='reservations.possiblereservation'),
        ),
    ]
