# Generated by Django 4.0.4 on 2022-05-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_possiblereservation_another_reservation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('external_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
