# Generated by Django 4.0.4 on 2022-10-31 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='minutes_to_auto_cancel',
            field=models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(121)]),
        ),
    ]
